apiVersion: batch/v1
kind: Job
metadata:
  namespace: example03
  generateName: cleanup-after-sync-
  labels:
    codefresh.io/cert: cleanup-job
  annotations:
<<<<<<< HEAD
      argocd.argoproj.io/hook: PostSync
=======
    argocd.argoproj.io/hook: PostSync
>>>>>>> 444a46c04c1a0b874da3cb0968a4ece84ef95741
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
